name: ApprovalTest
on:
  push:
    branches: 
      - main
jobs:
  noApproval:
    name: "Test Approval"
    runs-on: ubuntu-latest
    steps:
      - name: "No approval needed"
        run: |
          Console.WriteLine("This doesn't need approval");
      - name: "getting approval"
        uses: trstringer/manual-approval@v1
        with:
            secret: ${{ github.TOKEN }}
            approvers: mikeebowen,tomjebo
            minimum-approvals: 1
            issue-title: "Approval for publishing to Nuget.org"
            issue-body: "Please approve or deny the deployment to Nuget.org"
            exclude-workflow-initiator-as-approver: false
            additional-approved-words: ''
            additional-denied-words: ''
      - name: "this should need approval"
        run: |
          Console.WriteLine("this should need approval");
