name: ApprovalTest
on:
  workflow_run:
    workflows:
      - Package
    types:
      - completed
env:
  IS_RELEASE: 'false'
jobs:
  releaseInfo: 
    name: Check for Release
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Download Release Info
#       id: releaseData
      uses: dawidd6/action-download-artifact@v2
      with:
       run_id: ${{ github.event.workflow_run.id }}
       name: release-info
    - name: Check if workflow is release
      shell: pwsh
      id: releaseData
      run: |
        $isRelease = Get-Content -Path release-info.txt
        echo The result is $isRelease
        echo "This is IS_RELEASE = $env:IS_RELEASE"
        
        if ($isRelease -ne 'true') {
          echo "is not a release"
          echo "IS_RELEASE=true" >> $env:GITHUB_ENV
          echo "updated IS_RELEASE = $env:IS_RELEASE"
          exit 0
        }
  noApproval:
    name: "Test Approval"
    runs-on: ubuntu-latest
#     needs: [releaseInfo]
    if: env.IS_RELEASE == 'true'
    steps:
      - name: noApprove
        shell: pwsh
        run: |
           echo "This doesn't need approval"
           echo ${{ github.TOKEN }}
           echo "----------------------"
      - name: gettingApproval
        uses: trstringer/manual-approval@v1
        with:
            secret: ${{ github.TOKEN }}
            approvers: mikeebowen
            minimum-approvals: 1
            issue-title: "Approval for publishing to Nuget.org"
            issue-body: "Please approve or deny the deployment to Nuget.org"
            exclude-workflow-initiator-as-approver: false
            additional-approved-words: ''
            additional-denied-words: ''
      - name: thisShouldNeedApproval
        shell: pwsh
        run: |
          echo "this should need approval"
