name: ApprovalTest
on:
  workflow_run:
    workflows:
      - Package
    types:
      - completed
jobs:
  releaseInfo: 
    name: Check for Release
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Download Release Info
      uses: dawidd6/action-download-artifact@v2
      with:
       run_id: ${{ github.event.workflow_run.id }}
       name: release-info
       path: ${{ github.workspace }}/release-info.txt
    - name: Check is workflow is release
      shell: pwsh
      run: |
        echo "running powershell"
        $isRelease = Get-Content ${{ github.workspace }}/release-info.txt
        echo $isRelease
        
#   noApproval:
#     name: "Test Approval"
#     runs-on: ubuntu-latest
#     steps:
#       - name: noApprovalNeeded
#         shell: pwsh
#         run: |
#            echo "This doesn't need approval"
#            echo ${{ github.TOKEN }}
#            echo "----------------------"
#       - name: gettingApproval
#         uses: trstringer/manual-approval@v1
#         with:
#             secret: ${{ github.TOKEN }}
#             approvers: mikeebowen
#             minimum-approvals: 1
#             issue-title: "Approval for publishing to Nuget.org"
#             issue-body: "Please approve or deny the deployment to Nuget.org"
#             exclude-workflow-initiator-as-approver: false
#             additional-approved-words: ''
#             additional-denied-words: ''
#       - name: thisShouldNeedApproval
#         shell: pwsh
#         run: |
#           echo "this should need approval"
