name: ApprovalTest
on:
  workflow_run:
    workflows:
      - Package
    types:
      - completed
jobs:
  releaseInfo: 
    name: Check for Release
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      is_release: 'false'
    steps:
    - name: Download Release Info
#       id: releaseData
      uses: dawidd6/action-download-artifact@v2
      with:
       run_id: ${{ github.event.workflow_run.id }}
       name: release-info
    - name: Check if workflow is release
      shell: pwsh
      id: releaseData
      run: |
        $isRelease = Get-Content -Path release-info.txt
        echo The result is $isRelease
        if ($isRelease -eq 'true') {
          echo "is a release"
          echo "is_release=true" >> $GITHUB_OUTPUT
        }
  noApproval:
    name: "Test Approval"
    runs-on: ubuntu-latest
    needs: [releaseInfo]
    if: ${{ needs.releaseInfo.outputs.is_release == 'true' }}
    steps:
      - name: noApprove
        shell: pwsh
        run: |
           echo "This doesn't need approval"
           echo ${{ github.TOKEN }}
           echo "----------------------"
      - name: gettingApproval
        uses: trstringer/manual-approval@v1
        with:
            secret: ${{ github.TOKEN }}
            approvers: mikeebowen
            minimum-approvals: 1
            issue-title: "Approval for publishing to Nuget.org"
            issue-body: "Please approve or deny the deployment to Nuget.org"
            exclude-workflow-initiator-as-approver: false
            additional-approved-words: ''
            additional-denied-words: ''
      - name: thisShouldNeedApproval
        shell: pwsh
        run: |
          echo "this should need approval"
