name: ApprovalTest
on: 
  release:
    types: [published]
jobs:
  noApproval:
    name: "Test Approval"
    runs-on: ubuntu-latest
    steps:
      - name: noApprovalNeeded
        shell: pwsh
        run: |
           echo "This doesn't need approval"
           echo ${{ github.TOKEN }}
           echo "----------------------"
      - name: gettingApproval
        uses: trstringer/manual-approval@v1
        with:
            secret: ${{ github.TOKEN }}
            approvers: mikeebowen
            minimum-approvals: 1
            issue-title: "Approval for publishing to Nuget.org"
            issue-body: "Please approve or deny the deployment to Nuget.org"
            exclude-workflow-initiator-as-approver: false
            additional-approved-words: ''
            additional-denied-words: ''
      - name: thisShouldNeedApproval
        shell: pwsh
        run: |
          echo "this should need approval"
