name: ApprovalTest
on:
  workflow_run:
    workflows:
      - Package
    types:
      - completed
jobs:
  releaseInfo: 
    name: Check for Release
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      is_release: 'false'
    steps:
    - name: Download Release Info
#       id: releaseData
      uses: dawidd6/action-download-artifact@v2
      with:
       run_id: ${{ github.event.workflow_run.id }}
       name: release-info
    - name: Check if workflow is release
      shell: bash
      id: releaseData
      run: |
        isRelease=`cat release-info.txt`
        echo "isRelease = "
        echo $isRelease
        if [ "$isRelease" != true ]; then
          echo "is a release"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.REPOSITORY }}//actions/runs/${{ github.RUN_ID }}/cancel
        fi
  noApproval:
    name: "Test Approval"
    runs-on: ubuntu-latest
    needs: [releaseInfo]
#     if: needs.releaseInfo.outputs.is_release == 'true'
    steps:
      - name: noApprove
        shell: pwsh
        run: |
           echo "This doesn't need approval"
           echo ${{ github.TOKEN }}
           echo "----------------------"
      - name: gettingApproval
        uses: trstringer/manual-approval@v1
        with:
            secret: ${{ github.TOKEN }}
            approvers: mikeebowen
            minimum-approvals: 1
            issue-title: "Approval for publishing to Nuget.org"
            issue-body: "Please approve or deny the deployment to Nuget.org"
            exclude-workflow-initiator-as-approver: false
            additional-approved-words: ''
            additional-denied-words: ''
      - name: thisShouldNeedApproval
        shell: pwsh
        run: |
          echo "this should need approval"
